GET http://localhost:8080/users
###
GET http://localhost:8080/users/1
###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Bani",
  "email": "bani@gmail.com",
  "gender": "male"
}
###
PATCH http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Hasan",
  "email": "hasan@gmail.com",
  "gender": "male"
}
###
DELETE http://localhost:8080/users/2